### ISSUE TITLE
Auto add people to triage group

### ISSUE THREAD

**Issue by vmx** [ipld/auto#2]
I think it would be great that if we merge a PR from someone, that this person gets added to a team that has [triage permission](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level). This way you can also add this person to future code reviews.

I want that for the Multiformats org.

**Comment by rvagg** [comment]
closing for archival
